import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Foundations',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Core Concepts',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Advanced Topics',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-03',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Applications',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-04',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Capstone',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-05',
        },
      ],
    },
    {
      type: 'link',
      label: '🔍 Strict RAG Interface',
      href: '/rag',
    },
    {
      type: 'link',
      label: '🔧 MCP RAG Interface',
      href: '/mcp-rag',
    },
  ],
};

export default sidebars;